"""Fixed FK for Area and RoomCount

Revision ID: 5a7e93cd2107
Revises: a25d5e55788a
Create Date: 2024-04-07 12:49:16.671376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7e93cd2107'
down_revision: Union[str, None] = 'a25d5e55788a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('apartments_area_id_fkey', 'apartments', type_='foreignkey')
    op.drop_constraint('apartments_rooms_id_fkey', 'apartments', type_='foreignkey')
    op.create_foreign_key(None, 'apartments', 'room_counts', ['rooms_id'], ['id'])
    op.create_foreign_key(None, 'apartments', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.create_foreign_key('apartments_rooms_id_fkey', 'apartments', 'cities', ['rooms_id'], ['id'])
    op.create_foreign_key('apartments_area_id_fkey', 'apartments', 'cities', ['area_id'], ['id'])
    # ### end Alembic commands ###
