"""Added City, Area, and RoomCount models

Revision ID: a25d5e55788a
Revises: 
Create Date: 2024-04-07 12:26:50.413529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25d5e55788a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('room_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('apartments', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('area_id', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('rooms_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'apartments', 'cities', ['rooms_id'], ['id'])
    op.create_foreign_key(None, 'apartments', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'apartments', 'cities', ['area_id'], ['id'])
    op.drop_column('apartments', 'area')
    op.drop_column('apartments', 'city')
    op.drop_column('apartments', 'rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('rooms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('apartments', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('apartments', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.drop_column('apartments', 'rooms_id')
    op.drop_column('apartments', 'area_id')
    op.drop_column('apartments', 'city_id')
    op.drop_table('areas')
    op.drop_table('room_counts')
    op.drop_table('cities')
    # ### end Alembic commands ###
