"""Fixed Area relationship

Revision ID: bb7bf54ea064
Revises: f6ac193a1ea1
Create Date: 2024-04-09 22:56:16.208544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7bf54ea064'
down_revision: Union[str, None] = 'f6ac193a1ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('areas_city_id_fkey', 'areas', type_='foreignkey')
    op.drop_column('areas', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('areas_city_id_fkey', 'areas', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
