"""Fixed Area relationship

Revision ID: f6ac193a1ea1
Revises: e9c1ce62856c
Create Date: 2024-04-09 22:48:28.433210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ac193a1ea1'
down_revision: Union[str, None] = 'e9c1ce62856c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
